import test from 'node:test';
import assert from 'node:assert/strict';
import {SLOTS,local,at,upcoming,verifyText,sameSlot,sameText,DUENOX,FINANCE} from '../src/publisher.mjs';
test('exactly eight Riyadh slots',()=>assert.deepEqual(SLOTS,['07:30','09:00','10:30','12:00','16:00','18:00','20:00','22:00']));
test('prepares a slot before its due time',()=>{const q=upcoming(new Date('2026-10-01T06:59:00Z'));assert.equal(q.slot,'10:30');assert.equal(q.due.toISOString(),'2026-10-01T07:30:00.000Z');});
test('handles Riyadh timezone and date rollover',()=>{assert.equal(local(new Date('2026-10-01T20:40:00Z')).day,1);assert.equal(at({year:2026,month:10,day:2},'07:30').toISOString(),'2026-10-02T04:30:00.000Z');});
test('reviewed finance bank has varied safe messages',()=>{assert.equal(FINANCE.length,40);for(const item of FINANCE)assert.doesNotThrow(()=>verifyText(item),item);});
test('blocks politics, investment advice, URLs and missing hashtags',()=>{for(const t of ['انتخابات اليوم #تاسي','اشتر الآن #تاسي','خبر https://example.com #تاسي','منشور بدون هاشتاق'])assert.throws(()=>verifyText(t));assert.equal(verifyText('معلومات مالية محايدة. للعلم. #تاسي'),'معلومات مالية محايدة. للعلم. #تاسي');});
test('matches only the selected publication slot',()=>{const due=new Date('2026-10-01T09:00:00Z');assert.equal(sameSlot({dueAt:'2026-10-01T09:00:50Z'},due),true);assert.equal(sameSlot({dueAt:'2026-10-01T09:05:00Z'},due),false);});
test('prevents exact duplicate regardless of hashtag',()=>{assert.equal(sameText('أخبار السوق #تاسي',[{text:'أخبار السوق #الأسهم'}]),true);assert.equal(sameText('أخبار الذهب #ذهب',[{text:'أخبار السوق #الأسهم'}]),false);});
test('all approved DueNox drafts satisfy basic safety constraints',()=>{assert.equal(DUENOX.length,16);for(const text of DUENOX)assert.equal(verifyText(text),text);});
