
export const FEEDS=[
 {name:'أرقام - آخر الأخبار',url:'https://www.argaam.com/ar/rss/ho-main-news?sectionid=1523'},
 {name:'أرقام - نبض السوق',url:'https://www.argaam.com/ar/rss/ho-market-pulse?sectionid=70'},
 {name:'أرقام - الأسواق العالمية',url:'https://www.argaam.com/ar/rss/internationmarket-mainnewsar?sectionid=1334'},
 {name:'أرقام - الشركات',url:'https://www.argaam.com/ar/rss/companies?sectionid=1543'}
];
const BANNED=/(انتخاب|سياسي|حرب|هجوم|صراع|جيوسياس|إرهاب|روسيا|أوكرانيا|اوكرانيا|إسرائيل|اسرائيل|إيران|ايران|ترامب|بايدن|زيلينسكي|كرملين|war|attack|election|geopolitic)/iu;
const LOW=/(استقالة عضو|فتح باب الترشح|لجنة الترشيحات|دعوة مساهمي|اجتماع الجمعية|تعتزم إعلان نتائج|موعد إعلان نتائج|تعلن نتائجها بتاريخ)/iu;
const clean=s=>String(s||'').replace(/<!\[CDATA\[|\]\]>/giu,'').replace(/<[^>]+>/gu,' ').replace(/&nbsp;|&#160;/gu,' ').replace(/&amp;/gu,'&').replace(/\s+/gu,' ').trim();
function pick(b,t){const m=b.match(new RegExp('<'+t+'(?:\\s[^>]*)?>([\\s\\S]*?)<\\/'+t+'>','iu'));return clean(m?.[1]||'');}
export function parseRss(xml,feed=''){return [...String(xml).matchAll(/<item>([\s\S]*?)<\/item>/giu)].map(m=>{const b=m[1],description=[pick(b,'description'),pick(b,'content:encoded')].filter(Boolean).join(' ');return{title:pick(b,'title'),description,pubDate:pick(b,'pubDate'),feed};}).filter(x=>x.title);}
function ts(i){const x=Date.parse(i.pubDate);return Number.isFinite(x)&&i.feed.startsWith('أرقام')?x-10800000:x;}
export function category(i){const s=i.title+' '+i.description;if(/صح للصكوك|صكوك|سندات|أدوات الدين/iu.test(s))return'debt';if(/صندوق|صناديق|ريت|ETF|وحدات صندوق/iu.test(s))return'funds';if(/توزيعات نقدية|توزيع أرباح|عائد توزيعات/iu.test(s))return'dividend';if(/عقد.*% من الإيرادات|قيمة تتجاوز .*الإيرادات|ترسية.*عقد/iu.test(s))return'growth';if(/أرباح|خسائر|نتائج.*الربع|نتائج.*النصف|صافي الربح|الإيرادات/iu.test(s))return'results';if(/ملكية الأجانب|صافي مبيعات المؤسسات|صافي مشتريات|القيمة السوقية/iu.test(s))return'flows';if(/إنفاق المستهلكين|نقاط البيع|التجارة الإلكترونية/iu.test(s))return'consumer';if(/قروض|تمويل|الائتمان|ودائع|ساما|البنك المركزي السعودي/iu.test(s))return'banking';if(/وول ستريت|ناسداك|S&P|داو جونز|الأسهم الأمريكية|الأسهم الأميركية/iu.test(s))return'us';if(/تاسي|السوق السعودي|تداولات السوق/iu.test(s))return'market';if(/ذهب|فضة|نفط|برنت|خام|فائدة|أوقية/iu.test(s))return'macro';if(/هيئة السوق المالية|صناعة السوق|لائحة|قواعد/iu.test(s))return'regulation';return'other';}
const pref={0:['us','macro','debt'],1:['results','growth','dividend'],2:['market','flows','growth'],3:['results','consumer','banking'],4:['market','flows','regulation'],5:['funds','debt','dividend','macro'],7:['us','macro','growth','results']};
export function score(i,slot=0,now=new Date()){const age=(now-ts(i))/3600000;if(!Number.isFinite(age)||age<0||age>72||BANNED.test(i.title+' '+i.description)||LOW.test(i.title))return-999;const c=category(i);if(c==='other'||(!/\d/.test(all)&&c!=='regulation'))return-999;let v=({debt:12,funds:12,dividend:13,growth:15,results:15,flows:13,consumer:12,banking:12,us:13,market:12,macro:11,regulation:12,other:2}[c]||0);if(/\d/.test(i.title+i.description))v+=3;if(/%|مليار|مليون|تريليون|ريال|دولار|نقطة/iu.test(i.title+i.description))v+=4;if((pref[slot]||[]).includes(c))v+=8;return v-age/18;}
function short(s,n=112){s=clean(s);return[...s].length<=n?s:[...s].slice(0,n-1).join('').replace(/\s+\S*$/u,'')+'…';}
function src(i){const s=i.title+' '+i.description;return/ساما|البنك المركزي السعودي/iu.test(s)?'ساما/أرقام':/تداول السعودية/iu.test(s)?'تداول السعودية/أرقام':/هيئة السوق المالية/iu.test(s)?'هيئة السوق المالية/أرقام':/رويترز/iu.test(s)?'رويترز/أرقام':'أرقام';}
function tags(c,s){if(c==='growth')return'#أسهم_النمو #تاسي';if(c==='dividend')return'#أسهم_التوزيعات #تاسي';if(c==='funds')return'#الصناديق_الاستثمارية #تداول';if(c==='debt')return'#الصكوك #أدوات_الدين';if(c==='us')return'#الأسهم_الأمريكية #وول_ستريت';if(c==='flows')return'#تاسي #السيولة';if(c==='results')return'#نتائج_الشركات #تاسي';if(c==='banking')return'#البنوك #تاسي';if(c==='consumer')return'#الاقتصاد_السعودي #تاسي';if(c==='regulation')return'#هيئة_السوق_المالية #تاسي';if(c==='macro'&&/ذهب|فضة/iu.test(s))return'#الذهب #الأسواق_العالمية';if(c==='macro'&&/نفط|برنت|خام/iu.test(s))return'#النفط #الأسواق_العالمية';if(c==='macro')return'#الفائدة #الأسواق_العالمية';return'#تاسي #الأسهم_السعودية';}
export function buildInsight(i){const c=category(i),s=i.title+' '+i.description,h=tags(c,s),source=src(i);let t='';if(c==='consumer'){const a=i.title.match(/([\d,.]+)\s*مليار ريال/u)?.[1],g=i.title.match(/([\d.]+)\s*%/u)?.[1],ec=i.description.match(/التجارة الإلكترونية[\s\S]{0,220}/u)?.[0]||'',e=ec.match(/([\d,.]+)\s*مليار ريال/u)?.[1],eg=ec.match(/([\d.]+)\s*%/u)?.[1];if(a&&g&&e&&eg)t='📊 رقم اقتصادي لا يمر مرور الكرام: إنفاق المستهلكين '+a+' مليار ريال (+'+g+'%)، والتجارة الإلكترونية عبر مدى '+e+' مليار (+'+eg+'%). الزخم الرقمي هنا هو الرقم الأهم للمستثمر. المصدر: '+source+'. '+h;}
if(!t&&c==='banking'&&/قروض/iu.test(s)){const a=(i.title+i.description).match(/(?:إلى|نحو)\s*([\d,.]+)\s*مليار ريال/u)?.[1],g=i.title.match(/(?:بـ|بنسبة)\s*([\d.]+)%/u)?.[1];if(a&&g)t='🏦 الائتمان يتحرك: القروض وصلت '+a+' مليار ريال (+'+g+'% سنويًا). للمستثمر: نمو التمويل جيد فقط إذا حافظت البنوك على جودة الأصول ولم تقفز تكلفة المخاطر. المصدر: '+source+'. '+h;}
if(!t&&c==='flows'){t='💸 السيولة تتكلم: '+short(i.title,104)+'. لا أقرأ الرقم منفردًا؛ أقارنه باتجاه المؤشر ومشتريات الصناديق المحلية لمعرفة من يمتص البيع ومن يخرج. المصدر: '+source+'. '+h;}
if(!t&&c==='growth'){t='🚀 خبر نمو يستحق الحساب: '+short(i.title,105)+'. قارن قيمة العقد بإيرادات الشركة وهوامش التنفيذ ومدة الاعتراف بالإيراد؛ هنا تعرف هل الخبر سيغيّر الأرباح فعلًا أم لا. المصدر: '+source+'. '+h;}
if(!t&&c==='dividend'){t='💵 توزيعات تحت المجهر: '+short(i.title,103)+'. العائد النقدي وحده لا يكفي؛ الأهم تغطية التوزيع من التدفقات الحرة واستدامة الربح مقابل بدائل الدخل الثابت. المصدر: '+source+'. '+h;}
if(!t&&c==='results'){t='📈 نتيجة تستحق القراءة: '+short(i.title,103)+'. لا أتوقف عند نسبة نمو الربح: أبحث عن الإيرادات والهامش والتدفق النقدي وهل النمو تشغيلي أم من بند غير متكرر. المصدر: '+source+'. '+h;}
if(!t&&c==='funds'){t='🧺 في الصناديق: '+short(i.title,104)+'. قبل المقارنة راقب الأصل الذي يتتبعه الصندوق، الرسوم، التوزيعات والسيولة؛ هذه الأربعة أهم من اسم المنتج. المصدر: '+source+'. '+h;}
if(!t&&c==='debt'){t='💰 أدوات الدين: '+short(i.title,104)+'. قارن العائد بالمدة والسيولة وشروط الاسترداد؛ فرق بسيط في العائد قد لا يعوض تجميد السيولة أو حساسية السعر للفائدة. المصدر: '+source+'. '+h;}
if(!t&&c==='us'){t='🇺🇸 وول ستريت تحت المجهر: '+short(i.title,102)+'. للمستثمر لا يكفي اتجاه المؤشر؛ راقب عوائد الخزانة وقيادة شركات النمو واتساع المشاركة بين القطاعات. المصدر: '+source+'. '+h;}
if(!t&&c==='market'){t='📍 السوق الآن: '+short(i.title,105)+'. ما يهم خلف المؤشر: قيمة التداول، اتساع الصعود والقطاعات القائدة؛ اجتماع الثلاثة يعطي قراءة أقوى من لون تاسي وحده. المصدر: '+source+'. '+h;}
if(!t&&c==='macro'){t='🌍 رقم عالمي يهم المحافظ: '+short(i.title,102)+'. الأثر ينتقل إلى تكلفة التمويل وتقييم أسهم النمو وتسعير أدوات الدخل الثابت؛ لذلك لا أتعامل معه كخبر معزول. المصدر: '+source+'. '+h;}
if(!t&&c==='regulation'){t='⚖️ قرار سوق يستحق المتابعة: '+short(i.title,103)+'. الأثر الاستثماري يظهر في السيولة وكفاءة التسعير أو تكلفة الالتزام على الشركات، لا في عنوان القرار وحده. المصدر: '+source+'. '+h;}
if(!t)t='🔎 تحت المجهر: '+short(i.title,105)+'. أبحث عن أثر الخبر على الإيرادات أو الهوامش أو التدفقات أو التقييم؛ إذا لم يغير واحدًا منها فغالبًا أثره الاستثماري محدود. المصدر: '+source+'. '+h;return[...t].length<=280?t:null;}
const norm=s=>String(s||'').toLowerCase().replace(/#[\p{L}\p{N}_]+/gu,'').replace(/[^\p{L}\p{N}]+/gu,'');
export function chooseInsight(items,history=[],slot=0,now=new Date()){const rows=items.map(i=>({i,score:score(i,slot,now),text:buildInsight(i)})).filter(x=>x.score>0&&x.text).sort((a,b)=>b.score-a.score);return rows.find(x=>!history.some(p=>norm(p.text)===norm(x.text)))||null;}
async function fetchFeed(f){const r=await fetch(f.url,{headers:{'User-Agent':'Mozilla/5.0 X-Auto-Publisher/1.0'},signal:AbortSignal.timeout(12000)});if(!r.ok)throw Error(f.name+' HTTP '+r.status);return parseRss(await r.text(),f.name);}
export async function prepareLiveInsight(plan,history=[],now=new Date()){const settled=await Promise.allSettled(FEEDS.map(fetchFeed));const items=settled.flatMap(x=>x.status==='fulfilled'?x.value:[]);const c=chooseInsight(items,history,plan.index,now);if(!c)throw Error('No fresh high-value investment item');console.log('LIVE INSIGHT',category(c.i),c.score.toFixed(1),c.i.title);return c.text;}
export function parseTreasury(xml){const entries=[...String(xml).matchAll(/<entry>([\s\S]*?)<\/entry>/giu)];const rows=entries.map(m=>{const b=m[1],date=b.match(/<d:NEW_DATE[^>]*>([^<]+)<\/d:NEW_DATE>/iu)?.[1];const get=k=>Number(b.match(new RegExp('<d:'+k+'[^>]*>([^<]+)<\\/d:'+k+'>','iu'))?.[1]);return{date,mo3:get('BC_3MONTH'),yr2:get('BC_2YEAR'),yr10:get('BC_10YEAR'),yr30:get('BC_30YEAR')};}).filter(x=>x.date&&[x.mo3,x.yr2,x.yr10,x.yr30].every(Number.isFinite));return rows.sort((a,b)=>a.date.localeCompare(b.date)).at(-1)||null;}
export async function prepareDebtInsight(){const r=await fetch('https://home.treasury.gov/resource-center/data-chart-center/interest-rates/pages/xml?data=daily_treasury_yield_curve&field_tdr_date_value=2026',{headers:{'User-Agent':'Mozilla/5.0 X-Auto-Publisher/1.0'},signal:AbortSignal.timeout(12000)});if(!r.ok)throw Error('Treasury HTTP '+r.status);const x=parseTreasury(await r.text());if(!x)throw Error('Treasury yields unavailable');const slope=x.yr10-x.yr2;return'🏦 منحنى العائد الأمريكي: 3 أشهر '+x.mo3.toFixed(2)+'% | سنتان '+x.yr2.toFixed(2)+'% | 10 سنوات '+x.yr10.toFixed(2)+'% | 30 سنة '+x.yr30.toFixed(2)+'%. فرق 10س-2س '+(slope>=0?'+':'')+slope.toFixed(2)+' نقطة؛ رقم مهم لتقييم السندات وأسهم النمو. المصدر: الخزانة الأمريكية. #السندات #أدوات_الدين';}
