import {pathToFileURL} from 'node:url';
export const SLOTS=['07:30','09:00','10:30','12:00','16:00','18:00','20:00','22:00'];
const TZ='Asia/Riyadh', API='https://api.buffer.com';
const HOSTS=['saudiexchange.sa','argaam.com','sec.gov','nasdaq.com','nyse.com','federalreserve.gov','cmegroup.com','ice.com','theice.com'];
const TOPICS=['السوق السعودي وتاسي','إفصاحات الشركات السعودية','الأسهم الأمريكية وإفصاحات SEC','أسعار الذهب','النفط وعقوده','قرارات الفائدة من Federal Reserve','الصناديق الاستثمارية المتوافقة مع الشريعة','الأسهم السعودية أو الأمريكية'];
const BLOCK=/(انتخاب|سياس(?:ة|ي|يين)|حرب|جيوسياس|إرهاب|ارهاب|صراع|هجوم|اشتر|اشتري|شراء الآن|بع الآن|ادخل الآن|سهم ناري|انهيار|هدف مضمون|ربح مضمون|توصية|فرصة لا تعوض|buy now|sell now|guaranteed|election|geopolitic|warfare)/iu;
export const DUENOX=[
'هل ما زلت تتابع ديون العملاء في دفتر ورقي؟ يجمع DueNox حسابات العملاء والديون والدفعات في سجل رقمي. duenox.com #DueNox #إدارة_الديون',
'مع DueNox يمكنك تسجيل دفعات العملاء وتحديث حساباتهم. duenox.com #DueNox #المشاريع_الصغيرة',
'يتيح DueNox سجلًا للموردين لمتابعة حساباتهم من مكان واحد. duenox.com #DueNox #إدارة_الأعمال',
'إذا كان لمشروعك عدة فروع، يتيح DueNox إدارة الفروع والمستخدمين المرتبطين بكل فرع. duenox.com #DueNox #التجارة',
'من ميزات DueNox تحديد حد ائتماني للعملاء لتنظيم التعاملات الآجلة. duenox.com #DueNox #إدارة_الائتمان',
'يوفر DueNox القائمة السوداء للعملاء ضمن أدوات متابعة الحسابات. duenox.com #DueNox #إدارة_العملاء',
'يتيح DueNox تقارير وخيارات تصدير لمتابعة بيانات متجرك. duenox.com #DueNox #التقارير',
'يدعم DueNox العربية والإنجليزية، وتسجيل الدخول برمز OTP عبر البريد. duenox.com #DueNox #الأعمال',
'يوفر DueNox تنبيهات تساعدك على متابعة حسابات العملاء وإدارة الديون. duenox.com #DueNox #إدارة_المتاجر',
'تابع حسابات العملاء والموردين وسجّل الدفعات عبر DueNox. duenox.com #DueNox #التجارة',
'يوفر DueNox مستخدمين لكل فرع ضمن إدارة أعمالك. duenox.com #DueNox #الفروع',
'تتيح أدوات DueNox متابعة سجل العميل وحده الائتماني داخل النظام. duenox.com #DueNox #المتاجر',
'من دفتر العملاء إلى تقارير الأرصدة والتصدير: أدوات DueNox لمتابعة حسابات النشاط. duenox.com #DueNox #إدارة_الأعمال',
'احفظ سجل الدفعات والمبالغ المستحقة للعملاء في DueNox. duenox.com #DueNox #إدارة_الديون',
'واجهة DueNox بالعربية والإنجليزية تساعد على متابعة العملاء والفروع. duenox.com #DueNox #المشاريع_الصغيرة',
'ينظم DueNox حسابات الموردين والعملاء والدفعات في نظام واحد. duenox.com #DueNox #الموردين'
];
export function local(d=new Date()){return Object.fromEntries(new Intl.DateTimeFormat('en-GB',{timeZone:TZ,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(d).filter(p=>p.type!=='literal').map(p=>[p.type,Number(p.value)]));}
export function at(p,slot){const [h,m]=slot.split(':').map(Number);return new Date(Date.UTC(p.year,p.month-1,p.day,h-3,m));}
export function upcoming(now=new Date()){const p=local(now),base=new Date(Date.UTC(p.year,p.month-1,p.day,12));for(let day=0;day<=1;day++){const q=local(new Date(base.getTime()+day*86400000));for(let i=0;i<SLOTS.length;i++){const due=at(q,SLOTS[i]);const minutes=(due-now)/60000;if(minutes>=10&&minutes<=45)return{due,slot:SLOTS[i],index:i,day:q};}}return null;}
export function safeUrl(value){try{const u=new URL(value);return u.protocol==='https:'&&HOSTS.some(h=>u.hostname===h||u.hostname.endsWith('.'+h));}catch{return false;}}
export function verifyText(value){const t=String(value||'').trim();if(!t||[...t].length>280||BLOCK.test(t)||/https?:\/\//iu.test(t)||!/#\w|#[\p{L}\p{N}_]+/u.test(t))throw Error('Invalid or unsafe tweet');return t;}
export function sameSlot(post,due){return Boolean(post.dueAt&&Math.abs(new Date(post.dueAt).getTime()-due.getTime())<=120000);}
export function sameText(text,posts){const compact=t=>String(t||'').toLowerCase().replace(/#[\p{L}\p{N}_]+/gu,'').replace(/\s+/gu,'').trim();return posts.some(p=>compact(text)===compact(p.text));}
const pause=ms=>new Promise(r=>setTimeout(r,ms));
async function http(url,options={},timeout=20000){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeout);try{return await fetch(url,{...options,signal:controller.signal});}finally{clearTimeout(timer);}}
async function gql(query,token,retry=false){for(let i=0;i<(retry?3:1);i++){try{const r=await http(API,{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify({query})});if(!r.ok)throw Error('Buffer HTTP '+r.status);const data=await r.json();if(data.errors?.length)throw Error('Buffer GraphQL: '+data.errors.map(e=>e.message).join('; '));return data.data;}catch(e){if(!retry||i===2)throw e;await pause(1000*(i+1));}}}
async function posts(token,org,channel){const since=new Date(Date.now()-72*3600000).toISOString();let all=[],cursor=null;for(let i=0;i<4;i++){const query='query {posts(first:100,input:{organizationId:'+JSON.stringify(org)+',filter:{channelIds:['+JSON.stringify(channel)+'],status:[scheduled,sending,sent,error],createdAt:{start:'+JSON.stringify(since)+'}},sort:[{field:createdAt,direction:desc}]}' +(cursor?',after:'+JSON.stringify(cursor):'')+'){edges{node{id text status dueAt createdAt channelId}}pageInfo{hasNextPage endCursor}}}';const x=(await gql(query,token,true)).posts;all.push(...x.edges.map(e=>e.node));if(!x.pageInfo.hasNextPage)return all;cursor=x.pageInfo.endCursor;if(!cursor)throw Error('Buffer pagination failed');}throw Error('Buffer post list exceeded safety limit');}
async function prepareFinance(plan,history){const key=process.env.OPENAI_API_KEY;if(!key)throw Error('OPENAI_API_KEY missing');const prompt='ابحث بالويب عن خبر مالي موثوق وحديث خلال 48 ساعة عن '+TOPICS[plan.index]+'. استخدم المصادر الأصلية saudiexchange.sa, argaam.com, sec.gov, nasdaq.com, nyse.com, federalreserve.gov, cmegroup.com, ice.com فقط. تحقق من التاريخ والأرقام. ممنوع السياسة والانتخابات والحروب والتوصيات الاستثمارية والترويج والتوقعات؛ محتوى عربي وصفي محايد مع هاشتاق مناسب، أقل من 260 حرفًا، بلا روابط. لا تكرر هذه التغريدات: '+JSON.stringify(history.slice(0,20).map(p=>p.text.slice(0,110)))+'. أجب JSON فقط {"text":"...","sourceUrl":"https://...","sourceTitle":"...","publishedAt":"ISO datetime"} أو {"noNews":true}.';
const r=await http('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:'Bearer '+key,'Content-Type':'application/json'},body:JSON.stringify({model:process.env.OPENAI_MODEL||'gpt-5-mini',tools:[{type:'web_search'}],input:prompt})},90000);if(!r.ok)throw Error('OpenAI API HTTP '+r.status);const data=await r.json(),out=(data.output||[]).filter(x=>x.type==='message').flatMap(x=>x.content||[]).filter(x=>x.type==='output_text').map(x=>x.text).join('').trim();let item;try{item=JSON.parse(out.replace(/^\x60\x60\x60(?:json)?\s*/i,'').replace(/\s*\x60\x60\x60$/,''));}catch{throw Error('News response is not JSON');}
if(item.noNews)throw Error('No verifiable recent news');if(!safeUrl(item.sourceUrl))throw Error('Untrusted source');const age=Date.now()-new Date(item.publishedAt).getTime();if(!Number.isFinite(age)||age>48*3600000||age< -3600000)throw Error('Source date is not recent');const text=verifyText(item.text);if(sameText(text,history))throw Error('Duplicate news text');
const page=await http(item.sourceUrl,{headers:{'User-Agent':'X-Auto-Publisher/1.0'}},16000);if(!page.ok||!safeUrl(page.url||item.sourceUrl))throw Error('Original source inaccessible');const body=(await page.text()).slice(0,1500000).replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,' ').replace(/<[^>]+>/g,' ').toLowerCase();const words=String(item.sourceTitle||'').toLowerCase().split(/[^\p{L}\p{N}]+/u).filter(x=>x.length>3);if(words.length<2||words.filter(w=>body.includes(w)).length<2)throw Error('Source headline unverified');return text;}
function weekend(plan,history){const ordinal=Math.floor(Date.UTC(plan.day.year,plan.day.month-1,plan.day.day)/86400000);for(let offset=0;offset<DUENOX.length;offset++){const t=DUENOX[(ordinal*8+plan.index+offset)%DUENOX.length];if(!sameText(t,history))return verifyText(t);}throw Error('No unused DueNox post');}
export async function run(){const plan=upcoming();if(!plan){console.log('No slot in 10–45 minute preparation window');return;}console.log('Upcoming Riyadh slot',plan.slot,plan.due.toISOString());if(process.env.PUBLISH_ENABLED!=='true'){console.log('DRY RUN: publication disabled');return;}
const token=process.env.BUFFER_API_KEY,org=process.env.BUFFER_ORGANIZATION_ID,channel=process.env.BUFFER_CHANNEL_ID;if(!token||!org||!channel)throw Error('Buffer credentials/IDs missing');const history=await posts(token,org,channel);
if(history.some(p=>sameSlot(p,plan.due))){console.log('Already scheduled/sent for this slot');return;}
const overdue=history.filter(p=>p.dueAt&&p.status!=='sent'&&Date.now()-new Date(p.dueAt).getTime()>15*60000&&Date.now()-new Date(p.dueAt).getTime()<4*3600000&&SLOTS.some(s=>sameSlot(p,at(plan.day,s))));if(overdue.length)throw Error('Previous scheduled post not confirmed as sent');
if(history.some(p=>['scheduled','sending'].includes(p.status)&&new Date(p.dueAt)>new Date())){console.log('A future Buffer post already exists');return;}
const weekday=new Date(Date.UTC(plan.day.year,plan.day.month-1,plan.day.day)).getUTCDay(),text=(weekday===5||weekday===6)?weekend(plan,history):await prepareFinance(plan,history);
const fresh=await posts(token,org,channel);if(fresh.some(p=>sameSlot(p,plan.due)||sameText(text,[p])||(['scheduled','sending'].includes(p.status)&&new Date(p.dueAt)>new Date()))){console.log('Slot or content now covered; no duplicate');return;}
if(plan.due.getTime()-Date.now()<120000)throw Error('Too close to scheduled time');const query='mutation {createPost(input:{text:'+JSON.stringify(text)+',channelId:'+JSON.stringify(channel)+',schedulingType:automatic,mode:customScheduled,dueAt:'+JSON.stringify(plan.due.toISOString())+'}){... on PostActionSuccess{post{id dueAt status}}... on MutationError{message}}}';let created;try{created=(await gql(query,token)).createPost;}catch(error){const check=await posts(token,org,channel);if(check.some(p=>sameSlot(p,plan.due))){console.log('Creation recovered from Buffer history');return;}throw error;}if(created?.message||!created?.post?.id||!sameSlot(created.post,plan.due))throw Error('Buffer did not confirm correct scheduled post: '+(created?.message||''));console.log('Scheduled post',created.post.id,'at',created.post.dueAt);}
if(process.argv[1]&&import.meta.url===pathToFileURL(process.argv[1]).href)run().catch(e=>{console.error('PUBLISHER_FAILED:',e.message);process.exitCode=1;});
